service: api

provider:
  name: aws
  runtime: nodejs20.x

  environment: 
    PATIENT_GOAL_SETTINGS_TABLE: patientGoalSettings-boonxvym5fasde4r33wkfzd7yq-dev
    F_SETTING_TABLE: fSetting-boonxvym5fasde4r33wkfzd7yq-dev
    USER_FREQUENCY_TABLE: userFrequency-boonxvym5fasde4r33wkfzd7yq-dev

custom:
  serverless-offline:
    httpPort: 3000

functions:
  updateFrequency:
    handler: src/handlers/updateFrequency.handler
    events:
      - http:
          path: /frequency
          method: post

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies